# The name and key for this project in SonarQube
sonar.projectKey=evaluated-exercise-7
sonar.projectName=evaluated-exercise-7
sonar.projectVersion=1.0
# The relative path to the root of your source code
sonar.sources=./app
# The url to the SonarQube server
sonar.host.url=http://localhost:9000
# The login token for the SonarQube server
sonar.login=${SONAR_TOKEN}
